// src/app/home-module/components/projects/projects.component.ts
import { Component } from '@angular/core';
import { PROJECTS } from '../../mocks/projects.mock';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss']
})
export class ProjectsComponent {
  projects = PROJECTS
}

<section id="projects">
  <h1>Proyectos</h1>
  <section class="container">
    <app-project
      *ngFor="let project of projects"
      [name]="project.name"
      [description]="project.description"
      [image]="project.image"
      [techs]="project.techs"
      [links]="project.links"
    ></app-project>
  </section>
</section>

// components/Projects/Projects.tsx
import Project from './Project';
import styles from './Projects.module.css';
import { PJS } from './data';

export default function Projects(): JSX.Element {
  return (
    <div id='projects' className={styles.container}>
      <h1>Proyectos</h1>
      <div>
        {PJS.map((pro, index) => (
          <Project
            image={pro.image}
            name={pro.name}
            description={pro.description}
            techs={pro.techs}
            links={pro.links}
            key={`${pro.name}-${index}`}
          />
        ))}
      </div>
    </div>
  );
}
