// src/app/home-module/components/project/project.component.ts
import { Component, Input } from '@angular/core';
import { IUrl, ITech } from '../../interfaces/project.interface';
@Component({
  selector: 'app-project',
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.scss'],
})
export class ProjectComponent {
  @Input() name: string = '';
  @Input() description: string = '';
  @Input() image: string = '';
  @Input() links: IUrl[] = [];
  @Input() techs: ITech[] = [];
}


  <img [src]="image" [alt]="name" />
  <h1>{{ name }}</h1>
  <p>{{ description }}</p>
  <section class="techs_links">
    <section>
      <h3>Tecnologías</h3>
      <ul class="techs">
        <li *ngFor="let tech of techs">{{ tech.name }}</li>
      </ul>
    </section>
    <section class="section">
      <ul class="links">
        <li *ngFor="let link of links" [ngClass]="link.url != '#' ? 'url' : 'error'">
          <ng-container *ngIf="link.url != '#'; else not">
            <a [href]="link.url" target="_blank" rel="noopener noreferrer">{{
              link.name
            }}</a>
          </ng-container>
          <ng-template #not>
            <span>{{ link.name }}</span>
          </ng-template>
        </li>
      </ul>
    </section>
  </section>

// components/Projects/Project.tsx
import styles from './Project.module.css';

type Links = {
  url: string;
  name: string;
};

export type Card = {
  image: string;
  name: string;
  description: string;
  techs: string[];
  links: Links[];
};

export function Project(project: Card) {
  return (
    <div className={styles.container}>
      <img src={project.image} alt={project.name} />
      <h3>{project.name}</h3>
      <p>{project.description}</p>
      <h4>Algunas techs usadas</h4>
      <div>
        {project.techs.map((tech) => (
          <span>{tech}</span>
        ))}
      </div>
      {project.links.map((link) =>
        link.name.includes('En producción') ? (
          <span>{link.name}</span>
        ) : (
          <a href={link.url} target='_blank' rel='noopener noreferrer'>
            {link.name}
          </a>
        )
      )}
    </div>
  );
}
